### ISSUE TITLE
Some ANSI colors cause an error

### ISSUE THREAD

**Issue by dullbananas** [prompt-toolkit/python-prompt-toolkit#1011]
I am working on a [Python-based Unix shell](https://github.com/dullbananas/dish), and I am working on implementing usage of prompt_toolkit. When I try printing a dark green prompt, it works:

```python3
prompt(ANSI('\033[32m$\033[0;39;49m '))
```

But the light green prompt does not work:

```python3
prompt(ANSI('\033[38;2;144;238;144m$\033[0;39;49m '))
```

It causes this error to appear:

```text.python.traceback
Traceback (most recent call last):
  File "/home/dull/.local/bin/dish", line 14, in <module>
    dish.run()
  File "/home/dull/dish/dish/dish.py", line 18, in run
    cli.main.main(obj=self)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/Click-7.0-py3.8.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/Click-7.0-py3.8.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/Click-7.0-py3.8.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/Click-7.0-py3.8.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dull/dish/dish/cli.py", line 25, in main
    line = psession.prompt(prompt)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 925, in prompt
    return self.app.run()
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 781, in run
    return run()
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 754, in run
    return get_event_loop().run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 739, in run_async
    return await _run_async2()
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 724, in _run_async2
    result = await _run_async()
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 666, in _run_async
    self._redraw()
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 502, in _redraw
    self.context.run(run_in_context)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 488, in run_in_context
    self.renderer.render(self, self.layout)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 602, in render
    self._cursor_pos, self._last_style = _output_screen_diff(
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 204, in _output_screen_diff
    output_char(new_char)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 143, in output_char
    new_attrs = attrs_for_style_string[char.style]
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/renderer.py", line 267, in __missing__
    attrs = self.get_attrs_for_style_str(style_str)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/styles/style.py", line 377, in get_attrs_for_style_str
    return self._merged_style.get_attrs_for_style_str(style_str, default)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/styles/style.py", line 298, in get_attrs_for_style_str
    inline_attrs = _parse_style_str(part)
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/styles/style.py", line 158, in _parse_style_str
    attrs = attrs._replace(color=parse_color(part))
  File "/home/dull/.virtualenvs/dishdev/local/lib/python3.8/site-packages/prompt_toolkit/styles/style.py", line 75, in parse_color
    raise ValueError('Wrong color format %r' % text)
ValueError: Wrong color format '90ee90'
```

**Comment by jonathanslenders** [comment]
This is definitely a bug! Thanks for reporting. I'll push a fix asap.

**Comment by jonathanslenders** [comment]
See: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1018
Does that fix the issue?

**Comment by dullbananas** [comment]
Yes

**Comment by dullbananas** [comment]
What version will this fix be released in?
