### ISSUE TITLE
Printing a string that has "&" in it using with print_formatted_text won't work

### ISSUE THREAD

**Issue by evertonstz** [prompt-toolkit/python-prompt-toolkit#1019]
```python
from prompt_toolkit.validation import Validator, ValidationError
from prompt_toolkit import prompt, HTML, print_formatted_text as printft`

name = "everton & everton"
printft(HTML(f"<green>[DOWNLOAD] {name}</green>"))
```

Will raise the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/prompt_toolkit/formatted_text/html.py", line 33, in __init__
    document = minidom.parseString('<html-root>%s</html-root>' % (value, ))
  File "/usr/lib64/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib64/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib64/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 39
```

**Comment by jonathanslenders** [comment]
Hi @evertonstz,

This is expected. An ampersand requires to be escaped, when it represents a literal ampersand and not an entity. Write instead ``"everton &amp; everton"``.

Another solution (probably better) is to take advantage of the auto escaping of the ``HTML`` object:
```python
printft(HTML("<green>[DOWNLOAD] {name}</green>").format(name=name))
#or
printft(HTML("<green>[DOWNLOAD] %s</green>") % (name, ))
```

In this case, when the string interpolation is done on the ``HTML`` object rather then on the ``str``, the ``HTML`` class will take care of properly escaping things.

**Comment by evertonstz** [comment]
Hi, I knew I was doing something wrong! This solved the problem, thank you for taking the time!
