### ISSUE TITLE
Doesn't work in Jupyter Notebook

### ISSUE THREAD

**Issue by thoth291** [prompt-toolkit/python-prompt-toolkit#1066]
Dear prompt_toolkit Team!
Please advise on the situation below:

Simple example:
```python
from prompt_toolkit.shortcuts import ProgressBar
import time
from prompt_toolkit import __version__
print(__version__)

with ProgressBar() as pb:
    for i in pb(range(800)):
        time.sleep(.01)
```
For 2.0.9 gives this:
```python
Traceback (most recent call last):
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/shortcuts/progress_bar/base.py", line 157, in run
    self.app.run()
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 683, in run
    return f.result()
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 658, in _run_async2
    result = yield f
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/anaconda3/envs/intel-2019/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 610, in _run_async
    result = yield From(f)
EOFError
```

For  version 3.0.3:
```python
---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-1-c20cb4d79981> in <module>
      4 print(__version__)
      5 
----> 6 with ProgressBar() as pb:
      7     for i in pb(range(800)):
      8         time.sleep(.01)

/envs/pt/lib/python3.7/site-packages/prompt_toolkit/shortcuts/progress_bar/base.py in __init__(self, title, formatters, bottom_toolbar, style, key_bindings, file, color_depth, output, input)
    136         # works best with `patch_stdout`.
    137         self.color_depth = color_depth
--> 138         self.output = output or get_app_session().output
    139         self.input = input or get_app_session().input
    140 

/envs/pt/lib/python3.7/site-packages/prompt_toolkit/application/current.py in output(self)
     63             from prompt_toolkit.output.defaults import create_output
     64 
---> 65             self._output = create_output()
     66         return self._output
     67 

/envs/pt/lib/python3.7/site-packages/prompt_toolkit/output/defaults.py in create_output(stdout, always_prefer_tty)
     60         from .vt100 import Vt100_Output
     61 
---> 62         return Vt100_Output.from_pty(stdout, term=get_term_environment_variable())

/envs/pt/lib/python3.7/site-packages/prompt_toolkit/output/vt100.py in from_pty(cls, stdout, term)
    447         # this class often during unit tests as well. For convenience, we print
    448         # an error message, use standard dimensions, and go on.
--> 449         fd = stdout.fileno()
    450 
    451         if not stdout.isatty() and fd not in cls._fds_not_a_terminal:

UnsupportedOperation: fileno
```
Is it only for me - if so - could you please share your envlist?
If it happens with you too, then is there anyway to fix it or provide any workaround?

Thanks in Advance!

**Comment by jonathanslenders** [comment]
Hi @thoth291,

Prompt_toolkit is a terminal library: an ncurses or GNU Readline replacement. Web based front-ends are out af scope for this library.

Check out tqdm if you need Notebook integration.

Of course, it is be possible to implement a progress bar library on top of prompt_toolkit which uses this library if a terminal is detected, and which uses a different implementation if a Notebook is detected. Feel free to work on that if you're interested.

So, I'm closing this issue as out-of-scope.

**Comment by jonathanslenders** [comment]
What we could do however, is provide a better error message if someone tries to run any prompt_toolkit application in a Notebook.

I'll open the issue again to look into that.

**Comment by rojerian** [comment]
An informative error message would be great.  

Such a shame this mashup is technically impossible as, IMHO ... prompt_toolkit, questionary and notebooks would be a **killer toolkit** for a zillion use cases.
