### ISSUE TITLE
io.UnsupportedOperation: fileno  fd = stdout.fileno() on vt100.py line 449

### ISSUE THREAD

**Issue by itamarjp** [prompt-toolkit/python-prompt-toolkit#1136]
jupyter_console tests fails in prompt_toolkit/output/vt100.py line 449

fd = stdout.fileno()

with error io.UnsupportedOperation: fileno

example:

ERROR: test_call_pil_by_default (jupyter_console.tests.test_image_handler.ZMQTerminalInteractiveShellTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/jupyter_console-6.1.0/jupyter_console/tests/test_image_handler.py", line 32, in setUp
    self.shell = NonCommunicatingShell()
  File "/builddir/build/BUILD/jupyter_console-6.1.0/jupyter_console/ptshell.py", line 283, in __init__
    self.init_prompt_toolkit_cli()
  File "/builddir/build/BUILD/jupyter_console-6.1.0/jupyter_console/ptshell.py", line 447, in init_prompt_toolkit_cli
    self.pt_cli = PromptSession(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 458, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 701, in _create_application
    application: Application[_T] = Application(
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 266, in __init__
    self.output = output or session.output
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/application/current.py", line 65, in output
    self._output = create_output()
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/output/defaults.py", line 62, in create_output
    return Vt100_Output.from_pty(stdout, term=get_term_environment_variable())
  File "/usr/lib/python3.8/site-packages/prompt_toolkit/output/vt100.py", line 449, in from_pty
    fd = stdout.fileno()
io.UnsupportedOperation: fileno

you can see full logs here -> https://kojipkgs.fedoraproject.org//work/tasks/3927/44133927/build.log

**Comment by bnavigator** [comment]
In your setup, apparently nose captures stdout without a file descriptor.

If you run nosetests without capturing stdout (`-s` or `--nocapture`), `stdout` will have a file descriptor and prompt_toolkit won't run into the `UnsupportedOperation` exception.

**Comment by itamarjp** [comment]
thank you.
