### ISSUE TITLE
Create Layout that does not contain any Window object

### ISSUE THREAD

**Issue by plotski** [prompt-toolkit/python-prompt-toolkit#1257]
I want to initialize my layout with an empty `HSplit`. Children are added and removed later while the application is running. The first child is not available when I create the Layout.

```python
>>> from prompt_toolkit.layout import Layout
>>> from prompt_toolkit.layout.containers import HSplit
>>> Layout(HSplit(children=[]))
Traceback (most recent call last):
  File "/home/ich/code/upsies/venv/lib/python3.8/site-packages/prompt_toolkit/layout/layout.py", line 61, in __init__
    self._stack.append(next(self.find_all_windows()))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ich/code/upsies/venv/lib/python3.8/site-packages/prompt_toolkit/layout/layout.py", line 63, in __init__
    raise InvalidLayoutError(
prompt_toolkit.layout.layout.InvalidLayoutError: Invalid layout. The layout does not contain any Window object.
```
I tried replacing the exception with a `pass` in https://github.com/prompt-toolkit/python-prompt-toolkit/blob/10f5cca40f40f5dbda4c521ba72270b23f72628c/prompt_toolkit/layout/layout.py#L63 and the tests were passing, but then the `current_control` property broke. It looks like non-emptiness is built into the guts of the Layout class.

I could add an empty window, but that adds an empty line. I could remove that window when I've added the first real widget, but that's not very elegant or obvious why that's necessary.

**Comment by bobhy** [comment]
Try wrapping the window in a ConditionalContainer that is initially hidden.  This will not take up any height in the layout.  See `prompt-toolkit\shortcuts\prompt.py` for an example.  Maybe even use this approach for all your windows, if there's a predictable number of them?

**Comment by plotski** [comment]
Hey, thank you for your reply.

But this doesn't work because there are no Windows initially when the Layout is
created. The contents of the main HSplit are created dynamically while the
application is running.
