### ISSUE TITLE
Improper handling of stdin on exit - ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by JackofSpades707** [prompt-toolkit/python-prompt-toolkit#1456]
```
flask-shell-ptpython==1.0.2
ptpython==3.0.18
prompt-toolkit==3.0.19
Flask==1.1.2
click==7.1.2
```

This can be reproduced by installing `ptpython` and using this library (it does by default in most cases)
Then simply `exit()` the REPL.

<details>
<summary>Traceback</summary>

$ flask shell
\> exit()
> Traceback (most recent call last):
```python
  File "PROJECT_DIR/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask_shell_ptpython.py", line 37, in shell_command
    embed(globals=ctx)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/ptpython/repl.py", line 720, in embed
    repl.run()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/ptpython/repl.py", line 135, in run
    text = self.read()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/ptpython/python_input.py", line 1045, in read
    result = self.app.run(pre_run=pre_run, in_thread=True)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 874, in run
    raise exception
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 855, in run_in_thread
    result = self.run(
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 792, in _run_async2
    result = await _run_async()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 721, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 129, in raw_mode
    return raw_mode(self.stdin.fileno())
ValueError: I/O operation on closed file
```
</details>

**Comment by jonathanslenders** [comment]
This was fixed.
