### ISSUE TITLE
Unable to get confirmation prompt from bash script using prompt_toolkit

### ISSUE THREAD

**Issue by manojmanivannan** [prompt-toolkit/python-prompt-toolkit#1639]
I have a bash script, which asks for user confirmation,
so i have this simple prompt
```
#!/bin/bash

echo -e "from prompt_toolkit.shortcuts import confirm\nimport sys\nanswer=confirm('Do you want to delete table?')\nsys.exit(0) if answer else sys.exit(0)" | python3
```

running this i have EOFERROR

```Warning: Input is not a terminal (fd=0).
Do you want to delete table? (y/n)
^[[59;1RTraceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/mmanivannan/.local/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1504, in confirm
    return session.prompt()
  File "/home/mmanivannan/.local/lib/python3.10/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1034, in prompt
    return self.app.run(
  File "/home/mmanivannan/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 936, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mmanivannan/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 855, in run_async
    return await _run_async2()
  File "/home/mmanivannan/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 825, in _run_async2
    result = await _run_async()
  File "/home/mmanivannan/.local/lib/python3.10/site-packages/prompt_toolkit/application/application.py", line 753, in _run_async
    result = await f
EOFError
~ $ ;1R
```
I also see there is an open issue https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1143 and other issues are not helpful.
Any help is appreciated

**Comment by manojmanivannan** [comment]
I was expecting to wait for input from user.  is there an alternative way to wait for user input ? sorry for my ignorance.

**Comment by jonathanslenders** [comment]
Piping Python code in the REPL's stdin makes user input unavailable. The same is true for:

```
echo 'input()' | python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
EOFError: EOF when reading a line
```
Try this instead:

```sh
python -c "from prompt_toolkit.shortcuts import confirm;import sys;answer=confirm('Do you want to delete table?');sys.exit(0) if answer else sys.exit(0)"
```

**Comment by manojmanivannan** [comment]
Thanks @jonathanslenders , just what i was looking for.
