### ISSUE TITLE
importing pygments style raises exception (py 2.7)

### ISSUE THREAD

**Issue by rofl0r** [prompt-toolkit/python-prompt-toolkit#765]
```py
        #style = Style.from_dict(get_style_by_name(u'borland').styles),
        #style = style_from_pygments_dict(get_style_by_name(u'monokai').styles) 
        style = style_from_pygments_cls(get_style_by_name(u'monokai'))
        
        controls['codeview'] = TextArea(
                text = u'',
                read_only = True,
                scrollbar = True,
                line_numbers = True,
                wrap_lines = False,
                lexer=PygmentsLexer(CLexer),
                style = style,  
        ) 

```

```
Traceback (most recent call last):
  File "gdb.py", line 180, in <module>
    app = setup_app()
  File "gdb.py", line 120, in setup_app
    style = style,
  File "/lib/python2.7/site-packages/prompt_toolkit/widgets/base.py", line 197, in __init__
    style = 'class:text-area ' + style
TypeError: coercing to Unicode: need string or buffer, Style found
```
this is using the latest release 2.0.6

**Comment by rofl0r** [comment]
meanwhile i figured that in that scenario a "class:foo" style string is expected.
however using a pygments style even crashes in the Application's constructor, because the keys of the dict are objects, not strings.
i would like to combine a pygments style with my own styles...

```py
        styledict = {
                'gdbout':'bg:#000000 #888888',
                 ....
        }

        if False: # for some reason the keys into that dict are objects, not strings.
                pyg_style = get_style_by_name(u'borland').styles
                for x in pyg_style:
                        styledict[x] = pyg_style[x]

        style = Style.from_dict(styledict)

        app = Application(
                layout = Layout(
                        controls['root_container'],
                        focused_element=controls['input'],
                ),
                style=style,
                full_screen=True,
                key_bindings=merge_key_bindings([kb, load_sidebar_bindings('locals')]),
        )       

```

**Comment by jonathanslenders** [comment]
Hi @rofl0r,

Yes, I see how this is confusing. Probably we have to improve the documentation.

The ``style`` attributes for all container objects are style strings. This can refer to class names, but it can also contain inline styling.
The Pygments style class can be wrapped using ``prompt_toolkit.style.pygments.style_from_pygments_cls``. This turns it into a prompt_toolkit ``Style`` instance and can be passed to an ``Application``. (Not to a ``TextArea`` or any other UI component.)

In your example, the Pygments stuff would go in the ``styledict``. You can't include it directly, but it can be merged together:

```python
from prompt_toolkit.style import merge_styles

style_dict = merge_styles([
    style_dict,
    style_from_pygments_cls(get_style_by_name(u'monokai'))
])
```

**Comment by rofl0r** [comment]
hi @jonathanslenders, thanks for your reply.

here's the full example:
```py
from prompt_toolkit.styles import Style, style_from_pygments_cls, style_from_pygments_dict
from prompt_toolkit.styles import merge_styles
from pygments.styles import get_style_by_name

style_dict = {
    'gdbout':'bg:#000000 #888888',
}

style_dict = merge_styles([
    style_dict,
    style_from_pygments_cls(get_style_by_name(u'monokai'))
])

style = Style.from_dict(styledict)
```
that one doesn't work because style_from_pygments_cls() returns a style not a dict...
```
~ $ python2 mystyle.py
Traceback (most recent call last):
  File "mystyle.py", line 11, in <module>
    style_from_pygments_cls(get_style_by_name(u'monokai'))
  File "/lib/python2.7/site-packages/prompt_toolkit/styles/style.py", line 330, in merge_styles
    return _MergedStyle(styles)
  File "/lib/python2.7/site-packages/prompt_toolkit/styles/style.py", line 349, in __init__
    assert all(isinstance(style, BaseStyle) for style in styles)
AssertionError
```
and when we change it to:
```py
from prompt_toolkit.styles import Style, style_from_pygments_cls, style_from_pygments_dict
from prompt_toolkit.styles import merge_styles
from pygments.styles import get_style_by_name

style_dict = {
    'gdbout':'bg:#000000 #888888',
}

style_dict = merge_styles([
    style_dict,
    get_style_by_name(u'monokai').styles,
])

style = Style.from_dict(styledict)
```
this happens:
```
~ $ python2 -m pdb mystyle.py
> /home/rofl/mystyle.py(1)<module>()
-> from prompt_toolkit.styles import Style, style_from_pygments_cls, style_from_pygments_dict
(Pdb) c
Traceback (most recent call last):
  File "/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "mystyle.py", line 1, in <module>
    from prompt_toolkit.styles import Style, style_from_pygments_cls, style_from_pygments_dict
  File "/lib/python2.7/site-packages/prompt_toolkit/styles/style.py", line 330, in merge_styles
    return _MergedStyle(styles)
  File "/lib/python2.7/site-packages/prompt_toolkit/styles/style.py", line 349, in __init__
    assert all(isinstance(style, BaseStyle) for style in styles)
AssertionError
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /lib/python2.7/site-packages/prompt_toolkit/styles/style.py(349)__init__()
-> assert all(isinstance(style, BaseStyle) for style in styles)
(Pdb) p styles
[{'gdbout': 'bg:#000000 #888888'}, {Token.Generic.Output: '', Token.Generic.Emph: 'italic', Token.Comment.Hashbang: '', Token.Literal.String.Char: '', Token.Literal.String: '#e6db74', Token.Literal.Number.Oct: '', Token.Escape: '', Token.Comment.Single: '', Token.Literal.Number.Integer: '', Token.Name.Label: '', Token....
```
here the keys in the pygments style dict are some sort of objects...

**Comment by rofl0r** [comment]
oh wow, seems i got it working..
```py
from prompt_toolkit.styles import Style, style_from_pygments_cls, style_from_pygments_dict
from prompt_toolkit.styles import merge_styles
from pygments.styles import get_style_by_name

styledict = {
    'gdbout':'bg:#000000 #888888',
}

pygstyle = style_from_pygments_cls(get_style_by_name(u'monokai'))

style_dict = merge_styles([
    Style.from_dict(styledict),
    pygstyle
])

print type(style_dict)
```
