### ISSUE TITLE
Support ANSI color codes

### ISSUE THREAD

**Issue by martmists** [prompt-toolkit/python-prompt-toolkit#772]
Currently, it looks like this in prompt_toolkit:
![image](https://user-images.githubusercontent.com/16361449/47865137-b780c700-ddfb-11e8-8f21-f53fbd08e183.png)
But like this when just using `print()`:
![image](https://user-images.githubusercontent.com/16361449/47865160-c49db600-ddfb-11e8-9624-c618cd189a01.png)
Colors are received from a remote and may vary from line to line, so changing to a standard color scheme is not an option.

**Comment by martmists** [comment]
Yes, I did try to use `ANSI()` but it failed:
```
/usr/lib/python3.7/site-packages/pexpect/ANSI.py:29: UserWarning: pexpect.screen and pexpect.ANSI are deprecated. We recommend using pyte to emulate a terminal screen: https://pypi.python.org/pypi/pyte
  from . import screen

Traceback (most recent call last):
  ...
    self.generic_element.buffer.document = Document(text=ANSI(text), cursor_position=0)
  File "/usr/lib/python3.7/site-packages/pexpect/ANSI.py", line 200, in __init__
    term.__init__(self,r,c,*args,**kwargs)
  File "/usr/lib/python3.7/site-packages/pexpect/ANSI.py", line 191, in __init__
    screen.screen.__init__(self, r,c,*args,**kwargs)
  File "/usr/lib/python3.7/site-packages/pexpect/screen.py", line 102, in __init__
    self.w = [ [SPACE] * self.cols for _ in range(self.rows)]
TypeError: 'str' object cannot be interpreted as an integer
```
