### ISSUE TITLE
WordCompleter docs example throws AssertionError

### ISSUE THREAD

**Issue by MareoRaft** [prompt-toolkit/python-prompt-toolkit#808]
Hello,

I am using version 2.0.7 with python 2.7

    ~/programming/card-game-maxeta % pip install prompt_toolkit
    Requirement already satisfied: prompt_toolkit in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (2.0.7)
    Requirement already satisfied: wcwidth in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from prompt_toolkit) (0.1.7)
    Requirement already satisfied: six>=1.9.0 in /Library/Python/2.7/site-packages (from prompt_toolkit) (1.11.0)

and I am running the python file `pt_fun.py` whose contents is

    from prompt_toolkit import prompt
    from prompt_toolkit.completion import WordCompleter
    
    html_completer = WordCompleter(['<html>', '<body>', '<head>', '<title>'])
    text = prompt('Enter HTML: ', completer=html_completer)
    print('You said: %s' % text)

which is verbatim what is shown in the stable and 2.0.7 [docs](https://python-prompt-toolkit.readthedocs.io/en/2.0.7/pages/asking_for_input.html#autocompletion).

It throws the error:

    ~/programming/card-game-maxeta % python pt_fun.py
    Traceback (most recent call last):
      File "pt_fun.py", line 5, in <module>
        text = prompt('Enter HTML: ', completer=html_completer)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 840, in prompt
    ^[[32;1R    return session.prompt(*a, **kw)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 733, in prompt
        return run_sync()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 722, in run_sync
        return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 699, in run
        return run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 673, in run
        return f.result()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
        raise self._exception
    AssertionError

Thank you,
Matthew

**Comment by liuyangc3** [comment]
+1
I am using version 2.0.7 with python 2.7 too
```python
from __future__ import unicode_literals
from prompt_toolkit import prompt
from prompt_toolkit import print_formatted_text as pprint
from prompt_toolkit.styles import Style

style = Style.from_dict({
    # User input (default text).
    '':        '#ff0066',
    # Prompt.
    'pink':    '#884444',
    'green':   '#00aa00',
    'cyan':    'ansicyan',
})

message = [
    ('class', 'help for help'),
]

text = prompt(message, style=style)
```

It throws the error:
```
Traceback (most recent call last):
  File "t.py", line 20, in <module>
    text = prompt(message, style=style)
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 840, in prompt
    return session.prompt(*a, **kw)
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 733, in prompt
    return run_sync()
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 722, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 699, in run
    return run()
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 673, in run
    return f.result()
  File "/usr/lib/python2.7/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
AssertionError
```

**Comment by jonathanslenders** [comment]
@MareoRaft: in your example the error is that the prompt string is not a unicode object but str (in Python 2). Try to put a lowercase ``u` in front of the string:
```python

**Comment by liuyangc3** [comment]
@jonathanslenders 
thx, how can I use the defualt style ,  like `('', 'help for help'),` ?

**Comment by MareoRaft** [comment]
@jonathanslenders Thank you, it worked!

**Comment by MareoRaft** [comment]
@jonathanslenders  Please feel free to reopen if you want to use this ticket to make sure the error message gets updated.  Like you said, it really should be a better error message.
