### ISSUE TITLE
prompt-toolkit raises KeyError: ('', 1711583303320)

### ISSUE THREAD

**Issue by Code4SAFrankie** [prompt-toolkit/python-prompt-toolkit#854]
I get the following error:

E:\WPy-3710\python-3.7.1.amd64>python e:\Work\Python\repl.py
Traceback (most recent call last):
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\cache.py", line 34, in get
    return self._data[key]
KeyError: ('', 1711583303320)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\application\application.py", line 652, in _run_async2
    result = yield f
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\eventloop\coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\application\application.py", line 595, in _run_async
    self._redraw()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\application\application.py", line 444, in _redraw
    self.renderer.render(self, self.layout)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\renderer.py", line 546, in render
    layout.container.preferred_height(size.columns, size.rows).preferred)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 245, in preferred_height
    for c in self._all_children]
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 245, in <listcomp>
    for c in self._all_children]
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 639, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 245, in preferred_height
    for c in self._all_children]
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 245, in <listcomp>
    for c in self._all_children]
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 2179, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 1362, in preferred_height
    dont_extend=self.dont_extend_height())
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 1380, in _merge_dimensions
    preferred = get_preferred()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\containers.py", line 1357, in preferred_content_height
    self.get_line_prefix)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\controls.py", line 548, in preferred_height
    content = self.create_content(width, None)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\controls.py", line 667, in create_content
    document, width, height)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\controls.py", line 632, in _create_get_processed_line_func
    return create_func()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\controls.py", line 620, in create_func
    get_line = self._get_formatted_text_for_line_func(document)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\controls.py", line 577, in _get_formatted_text_for_line_func
    return self._fragment_cache.get(key, get_formatted_text_for_line)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\cache.py", line 37, in get
    value = getter_func()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\layout\controls.py", line 574, in get_formatted_text_for_line
    return self.lexer.lex_document(document)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\lexers\base.py", line 73, in lex_document
    assert isinstance(lexer, Lexer)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Work\Python\repl.py", line 14, in <module>
    lexer = SqlLexer
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 840, in prompt
    return session.prompt(*a, **kw)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 733, in prompt
    return run_sync()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 722, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\application\application.py", line 699, in run
    return run()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\application\application.py", line 673, in run
    return f.result()
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\eventloop\future.py", line 149, in result
    raise self._exception
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\eventloop\coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "E:\WPy-3710\python-3.7.1.amd64\lib\site-packages\prompt_toolkit\application\application.py", line 654, in _run_async2
    assert not self._is_running
AssertionError

when running:

from prompt_toolkit import prompt
from prompt_toolkit.history import FileHistory
from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
#from prompt_toolkit.contrib.completers import WordCompleter
from pygments.lexers.sql import SqlLexer

#SQLCompleter = WordCompleter(['SELECT', 'FROM', 'WHERE'], ignore_case = True)

while 1:
    inp = prompt(u'>',
        history = FileHistory('history.txt'),
        auto_suggest = AutoSuggestFromHistory(),
        #completer = SQLCompleter,
        lexer = SqlLexer
    )
    print(inp)

on: 

WinPython 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32

**Comment by jonathanslenders** [comment]
Hi @Code4SAFrankie,

The lexer you pass to the prompt function has to be a prompt_toolkit lexer. Try wrapping it in a ``PygmentsLexer``:

```python
from prompt_toolkit.lexer import PygmentsLexer

lexer = PygmentsLexer(SqlLexer)
```

**Comment by Code4SAFrankie** [comment]
Thanks, but that gives me:

Traceback (most recent call last):
  File "e:\work\Python\repl.py", line 7, in <module>
    from prompt_toolkit.lexer import PygmentsLexer
ModuleNotFoundError: No module named 'prompt_toolkit.lexer'

**Comment by Code4SAFrankie** [comment]
Fixed it with:
from prompt_toolkit.lexers import PygmentsLexer
