### ISSUE TITLE
Progress bar with asyncio loop?

### ISSUE THREAD

**Issue by taimurrabuske** [prompt-toolkit/python-prompt-toolkit#882]
Is it supposed do work together? I am getting:

Traceback (most recent call last):    |   1/1600  [00:00<00:07, 203.38it/s]
  File "/opt/python/3.7.3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/progress_bar/base.py", line 157, in run
    self.app.run()
  File "/opt/python/3.7.3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/opt/python/3.7.3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 682, in run
    run_until_complete(f, inputhook=inputhook)
  File "/opt/python/3.7.3/lib/python3.7/site-packages/prompt_toolkit/eventloop/defaults.py", line 123, in run_until_complete
    return get_event_loop().run_until_complete(future, inputhook=inputhook)
  File "/opt/python/3.7.3/lib/python3.7/site-packages/prompt_toolkit/eventloop/asyncio_posix.py", line 36, in run_until_complete
    return self.loop.run_until_complete(future)
  File "/opt/python/3.7.3/lib/python3.7/site-packages/nest_asyncio.py", line 56, in run_until_complete
    f = asyncio.ensure_future(future)
  File "/opt/python/3.7.3/lib/python3.7/asyncio/tasks.py", line 590, in ensure_future
    return ensure_future(_wrap_awaitable(coro_or_future), loop=loop)
  File "/opt/python/3.7.3/lib/python3.7/asyncio/tasks.py", line 580, in ensure_future
    loop = events.get_event_loop()
  File "/opt/python/3.7.3/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-20'.
There is no current event loop in thread 'Thread-20'.

However, my use case is rather unconventional since I have multiple event-loops coexisting: Tk, Qt5 and asyncio. Before investigating further, I would like to know if the current implementation of the progress bar is expected to work when the prompt_toolkit app uses only the asyncio event loop.

**Comment by jonathanslenders** [comment]
I will look into it. Right now, I'm working on a Python3 only upgrade of prompt_toolkit that uses asyncio natively everywhere. When that's done, I don't think we still have this issue.

**Comment by taimurrabuske** [comment]
Awesome!
This seems to me like the best design choice since python 2 will retire by the end of the year.
