### ISSUE TITLE
Incomprehensible error while using prompt() with grammar, lexer, and completer

### ISSUE THREAD

**Issue by mpenning** [prompt-toolkit/python-prompt-toolkit#905]
I'm running the git head version of `prompt_toolkit` to build what should be a simple test that's similar to [`regular-language.py`](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/regular-language.py); however, my test fails with an error that seemingly says nothing about the real problem.

This is the test:

```python
"""Loosely based on
https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/regular-language.py"""

from prompt_toolkit import prompt
from prompt_toolkit.completion import WordCompleter
from prompt_toolkit.contrib.regular_languages.compiler import compile
from prompt_toolkit.contrib.regular_languages.completion import (
    GrammarCompleter,
)
from prompt_toolkit.contrib.regular_languages.lexer import GrammarLexer
from prompt_toolkit.lexers import SimpleLexer
from prompt_toolkit.styles import Style

operators1 = ['show']
objects1 = ['log', 'jobs']

operators2 = ['kill', 'run']

def create_grammar():
    compile(r"""
    (\s* (?P<operator1>\w+) \s+ (?P<object1>\w+) \s*) |
    (\s* (?P<operator2>\w+) \s+ (?P<var2>\w+) \s*)
    """)

cmd_style = Style.from_dict({
    'operator':       '#33aa33 bold',
    'object':         '#ff0000 bold',
    'var':            '#ffff00 bold',

    'trailing-input': 'bg:#662222 #ffffff',
})

if __name__=='__main__':
    gg = create_grammar()

    ## Class names should match regex names found in the grammar
    lexer = GrammarLexer(gg,
        lexers={
            'operator1': SimpleLexer('class:operator'),
            'object1':   SimpleLexer('class:object'),

            'operator2': SimpleLexer('class:operator'),
            'var2':      SimpleLexer('class:var'),
            })

    completer = GrammarCompleter(gg, {
        'operator1': WordCompleter(operators1),
        'object1': WordCompleter(objects1),

        'operator2': WordCompleter(operators2),
    })

    try:
        while True:
            text = prompt('shell> ', lexer=lexer, completer=completer,
                          style=cmd_style)

    except EOFError:
        pass
```

When I run this, I get the error found below.  My concern is twofold:
- First, what should I do to make this run correctly?
- Second, the error handling in this case is quite shall we say "perl-esque"; by this I mean, the error is rather byzantine and seems to have nothing to do with anything I can identify in my code.

Thoughts?

```
(py36_test) [mpenning@mudslide python-prompt-toolkit]$ python that.py
Traceback (most recent call last):
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/cache.py", line 47, in get
    return self._data[key]
KeyError: ('', 139801200009168)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "that.py", line 58, in <module>
    style=None)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/shortcuts/prompt.py", line 1270, in prompt
    pre_run=pre_run)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/shortcuts/prompt.py", line 928, in prompt
    return self.app.run()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/application/application.py", line 749, in run
    return run()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/application/application.py", line 721, in run
    get_event_loop().run_until_complete(f)
  File "/opt/python36/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/application/application.py", line 706, in run_async
    return await _run_async2()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/application/application.py", line 697, in _run_async2
    result = await _run_async()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/application/application.py", line 640, in _run_async
    self._redraw()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/application/application.py", line 489, in _redraw
    self.context.run(run_in_context)
  File "/opt/virtual_env/py36_test/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/application/application.py", line 475, in run_in_context
    self.renderer.render(self, self.layout)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/renderer.py", line 562, in render
    layout.container.preferred_height(size.columns, size.rows).preferred)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 301, in preferred_height
    for c in self._all_children]
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 301, in <listcomp>
    for c in self._all_children]
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 716, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 301, in preferred_height
    for c in self._all_children]
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 301, in <listcomp>
    for c in self._all_children]
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 2329, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 1466, in preferred_height
    dont_extend=self.dont_extend_height())
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 1488, in _merge_dimensions
    preferred = get_preferred()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 1461, in preferred_content_height
    self.get_line_prefix)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 587, in preferred_height
    content = self.create_content(width, height=1)  # Pass a dummy '1' as height.
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 701, in create_content
    document, width, height)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 665, in _create_get_processed_line_func
    return create_func()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 653, in create_func
    get_line = self._get_formatted_text_for_line_func(document)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 617, in _get_formatted_text_for_line_func
    return self._fragment_cache.get(key, get_formatted_text_for_line)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/cache.py", line 50, in get
    value = getter_func()
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/layout/controls.py", line 614, in get_formatted_text_for_line
    return self.lexer.lex_document(document)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/lexers/base.py", line 74, in lex_document
    return lexer.lex_document(document)
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/contrib/regular_languages/lexer.py", line 80, in lex_document
    lines = list(split_lines(self._get_text_fragments(document.text)))
  File "/home/mpenning/python-prompt-toolkit/prompt_toolkit/contrib/regular_languages/lexer.py", line 42, in _get_text_fragments
    m = self.compiled_grammar.match_prefix(text)
AttributeError: 'NoneType' object has no attribute 'match_prefix'
(py36_test) [mpenning@mudslide python-prompt-toolkit]$
```

**Comment by mpenning** [comment]
I found the problem... I did not put a "return" in `create_grammar()`
