### ISSUE TITLE
assertion in print_formatted_text

### ISSUE THREAD

**Issue by jnwatson** [prompt-toolkit/python-prompt-toolkit#915]
prompt toolkit version 2.0.9

Example code:
```
from prompt_toolkit import print_formatted_text
print_formatted_text('Hello world\r')
```
Output:
```
Traceback (most recent call last):
  File "/tmp/pttest.py", line 3, in <module>
    print_formatted_text('Hello world\r')
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/shortcuts/utils.py", line 124, in print_formatted_text
    style_transformation=style_transformation)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/prompt_toolkit/renderer.py", line 674, in print_formatted_text
    assert '\r' not in text
AssertionError
```
I might suggest that an assertion isn't appropriate here, given that `print_formatted_text` is used as a substitute for `print`

**Comment by jonathanslenders** [comment]
Hi @jnwatson,

If you have some time, feel free to create a pull request here that removes carriage returns. (Exactly like done in your project.)
This can then be merged in both the 2.0 and master branch.
