### ISSUE TITLE
Is there a way to debug using pdb?

### ISSUE THREAD

**Issue by joaqo** [prompt-toolkit/python-prompt-toolkit#956]
I am trying out the progress bar scripts, in particular the simple progress bar, and I noticed it doesn't let me use `ipdb`. For example if I run

```python
#!/usr/bin/env python
"""
A very simple progress bar which keep track of the progress as we consume an
iterator.
"""
import time

from prompt_toolkit.shortcuts import ProgressBar


def main():
    with ProgressBar() as pb:
        for i in pb(range(800)):
            import ipdb; ipdb.set_trace()
            time.sleep(.01)


if __name__ == '__main__':
    main()
```

I get the following error:

```bash
Future exception was never retrieved
future: <prompt_toolkit.eventloop.future.Future object at 0x11013ee48>
Traceback (most recent call last):
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 658, in _run_async2
    result = yield f
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 598, in _run_async
    with self.input.attach(read_from_input):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/input/vt100.py", line 147, in _attached_input
    loop.add_reader(fd, callback)
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 272, in add_reader
    self.selector.register(fd)
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/eventloop/select.py", line 76, in register
    sel.register(fd)
  File "/Users/joaqo/.virtualenvs/deleteme/lib/python3.7/site-packages/prompt_toolkit/eventloop/select.py", line 131, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py", line 517, in register
    key = super().register(fileobj, events, data)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py", line 242, in register
    .format(fileobj, key.fd))
KeyError: '0 (FD 0) is already registered'
```

Is there a way to work with debuggers using python-prompt-toolkit?

**Comment by jonathanslenders** [comment]
Hi @joaqo,

Can you try normal pdb instead of ipdb? Ipdb is not going to work because it uses prompt_toolkit itself internally, and we don't have a good way to run multiple applications concurrently.

I think pdb should work, but it's possible that the active progress bar will overwrite the pdb output from the other thread. Maybe have a look at wdb too: https://github.com/Kozea/wdb

**Comment by joaqo** [comment]
Hey, thanks for the answer, had no idea ipdb used prompt-toolkit. Pdb doesn't error out, but its not really usable, it gets overwritten and I cant write text into it.
